### ISSUE TITLE
hitting 'go back' on a permission error page doesn't work

### ISSUE THREAD

**Issue by andrewjs18** [Sama34/OUGC-Feedback#10]
if you try to 'add feedback' as a guest, and the permissions are set so that you're not allowed to do that, it'll throw an error which is normal.  but when you try to hit the 'go back' button inside the pop up window, it just keeps reloading the window.  if you click on the X button, it closes as expected.

tested in firefox and chrome; both browsers can be used to reproduce this bug.

edited to add: wouldn't it just be easier to hide that button for any groups that do not have the proper permissions to use the feedback system?

![192 apr 23](https://cloud.githubusercontent.com/assets/2748980/7309792/e8450278-e9f0-11e4-87ab-500869dc11f1.jpg)

**Comment by Sama34** [comment]
If you have not permission then the link shouldn't appear in the first place, therefor the visibility of the button is irrelevant.

I suppose the proper _fix_ would be to remove the following line:
https://github.com/Sama34/OUGC-Feedback/blob/master/Upload/feedback.php#L58

But even so guest are not meant to be allowed to add feedback so removing that permission from them should fix the issue for you.

I thought about doing that for you during installation but I din't bother, honestly.

**Comment by andrewjs18** [comment]
changing the permissions worked fine.

I do agree, guests by default should not see the feedback button.
