### ISSUE TITLE
Quick-Reply hanging

### ISSUE THREAD

**Issue by p00lz** [Sama34/OUGC-Feedback#11]
When using quickreply it seems to hang.  
The post gets made but it won't automatically reload the page at the post.
Disabled and tried again, worked fine, Re-enabled and the problem came back

Jquery 2.1.4
PHP 5.4 & 5.6
Error shows in browser console;
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data  ---  jquery.min.js:4:5491

**Comment by Sama34** [comment]
MyBB 1.8 uses jQuery 1.x whereas you are using jQuery 2.x Can you confirm the issue reverting the the official supported library?

**Comment by p00lz** [comment]
1.11.3 - SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data jquery.min.js:5:15990

1.11.2 (bundled with mybb 1.8) - SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data jquery.min.js:4:15940

I thought it may be an issue with Quick Advanced Editors auto draft saving... appears to make no difference.  No difference when disabling Quick Advanced Editor altogether either

**Comment by Sama34** [comment]
Can you confirm this does fixes the issue @p00lz ?

**Comment by p00lz** [comment]
Yep the issue appears to be fixed with the included 1.11.2 jquery.

Testing with 2.1.4 also seems to work flawlessly now

**Comment by p00lz** [comment]
Just noticed this has introduced something else.

If a thread is started by somebody who can receive feedback this returns when opening it

MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
    1054 - Unknown column 'f.pid' in 'field list'
Query:
    SELECT f.pid FROM mybb_ougc_feedback fLEFT JOIN mybb_posts p ON (p.pid=f.pid) WHERE f.fuid='4' AND p.pid IN('55002','55004','55008','55009','55027','55041','55045','55050','55053','55067')

**Comment by Sama34** [comment]
There was actually a typo in there that was probably causing the issue. Uninstalling probably worked but the issue would arise eventually again.
