### ISSUE TITLE
cannot delete and/or remove feedback

### ISSUE THREAD

**Issue by andrewjs18** [Sama34/OUGC-Feedback#12]
whenever I try to delete and/or remove (what's the difference between the two anyway?!) it throws an 'invalid user' error.

![194 may 08](https://cloud.githubusercontent.com/assets/2748980/7544327/fc6e322e-f599-11e4-9796-6e355249afcd.jpg)

**Comment by Sama34** [comment]
Yeah I think I have yet to write much of that page.

> what's the difference between the two anyway?!

Take _remove_ as a _soft delete_.

**Comment by andrewjs18** [comment]
ok, thanks.  consider this as a friendly reminder then.  =)

**Comment by andrewjs18** [comment]
any updates on this @Sama34

**Comment by Sama34** [comment]
I honestly lack the time at the moment. Will comeback to personal plugins once I finish my paid work :(
