### ISSUE TITLE
apostrophes are not being parsed in the feedback comments

### ISSUE THREAD

**Issue by andrewjs18** [Sama34/OUGC-Feedback#5]
see attached image:
![cjcy2uy](https://cloud.githubusercontent.com/assets/2748980/7211897/da9b3ce0-e52d-11e4-9187-fbce222fa3a2.jpg)

**Comment by dragonexpert** [comment]
http://community.mybb.com/thread-167620-post-1154145.html#pid1154145

**Comment by Sama34** [comment]
Double escaping was actually the issue.
