### ISSUE TITLE
Edit button visible to allregular users

### ISSUE THREAD

**Issue by ScSi009** [Sama34/OUGC-Feedback#9]
Tested it with different accounts (admin, regular user), but doesn't do anything. Also, question is if the 'edit' button should be visible at all for regular users?

If any questions, don't hesitate to contact me.

**Comment by Sama34** [comment]
Please see #7

**Comment by ScSi009** [comment]
Report button fixed, should I open a new issue for the edit button?

**Comment by Sama34** [comment]
I just updated the title. Will checked it later but IIRC the permissions for buttons display was already correct. It was just that most of them did nothing.
